/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef test_CONSTANTS_H
#define test_CONSTANTS_H

#include "test_types.h"

namespace test {

class testConstants {
 public:
  testConstants();

};

extern const testConstants g_test_constants;

} // namespace

#endif
